version: "3"
services:
  nginx-timetrackerservice:
    image: nginx:latest
    ports:
      - "3699:80"
    volumes:
      - .:/var/www/html
      - ./var/nginx/conf.d-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-timetrackerservice

  php-timetrackerservice:
    image: php-timetrackerservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
#    mem_limit: 128m
#    memswap_limit: 128m
