version: "3"
services:
  nginx-timetrackerservice:
    image: nginx:latest
    ports:
      - "3699:80"
    volumes:
      - .:/var/www/html
      - ./config/nginx/conf.d-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-timetrackerservice

  php-timetrackerservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-timetrackerservice:latest
    env_file:
      - config/environment/dev/common.env
      - config/environment/dev/mariadb.env
    volumes:
      - .:/var/www/html
      - ./config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    links:
      - mariadb-timetrackerservice

  mariadb-timetrackerservice:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: timetracker
      MYSQL_PASSWORD: time1234
      MYSQL_DATABASE: timetracking
    volumes:
      - ./config/mariadb/migrate:/docker-entrypoint-initdb.d
      - ./config/mariadb/confd:/etc/mysql/conf.d
    ports:
      - "3306/tcp"