version: "3.7"
services:
  timetrackerservice-php:
    image: php-fpm-alpine:prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: "unless-stopped"
    env_file:
      - infrastructure/environment/prod/common.env
      - infrastructure/environment/prod/mariadb.env