version: "3"
services:
  timetrackerservice-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-alpine:prod
    restart: "always"
    env_file:
      - infrastructure/environment/prod/common.env
      - infrastructure/environment/prod/mariadb.env