version: "3.7"
services:
  timetrackerservice-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-alpine:dev
    env_file:
      - infrastructure/environment/dev/common.env
      - infrastructure/environment/dev/mariadb.env
    volumes:
      - .:/var/www/html
    links:
      - timetrackerservice-mariadb

  timetrackerservice-nginx:
    image: nginx:latest
    ports:
      - "3699:80"
    volumes:
      - .:/var/www/html
      - ./infrastructure/nginx/dev/conf.d-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - timetrackerservice-php

  timetrackerservice-mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: timetracker
      MYSQL_PASSWORD: time1234
      MYSQL_DATABASE: timetracking
    volumes:
      - ./infrastructure/mariadb/migrate:/docker-entrypoint-initdb.d
      - ./infrastructure/mariadb/confd:/etc/mysql/conf.d
    ports:
      - "3306/tcp"