version: '2.2'
services:
  timetrackerservice:
    image: timetrackerservice:latest
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - .:/var/www/html
#    ports:
#      - 888:80
#    mem_limit: 128m
#    memswap_limit: 128m
