# https://symfony.com/doc/current/validation.html

App\Usecase\GetEntity\GetEntityRequest:
  properties:
    date:
      - Date: ~

App\Usecase\DeleteEntity\DeleteEntityRequest:
  properties:
    date:
      - Date: ~

App\Usecase\AddEntity\AddEntityRequest:
  properties:
    date:
      - Date: ~

App\Usecase\ChangeEntity\ChangeEntityRequest:
  properties:
    date:
      - Date: ~