# https://symfony.com/doc/current/validation.html

App\Usecase\GetEntity\GetEntityRequest:
  properties:
    date:
      - Date: ~

App\Usecase\DeleteEntity\DeleteEntityRequest:
  properties:
    date:
      - Date: ~

App\Usecase\AddEntity\AddEntityRequest:
  properties:
    date:
      - Date: ~
    begin:
      - Length:
          min: 10
          max: 13

App\Usecase\ChangeEntity\ChangeEntityRequest:
  properties:
    date:
      - Date: ~
    begin:
      - Length:
          min: 10
          max: 13
    end:
      - Length:
          min: 10
          max: 13