GetAllEntries:
  path: /tracking
  controller: App\Controller\MainController::getAllEntries
  methods: [GET]

GetEntry:
  path: /tracking/{date}
  controller: App\Controller\MainController::getEntry
  methods: [GET]

#AddAntry:
#  path: /tracking
#  controller: App\Controller\MainController::addAntry
#  methods: [PUT]
#
#ChangeEntry:
#  path: /tracking/{date}
#  controller: App\Controller\MainController::changeEntry
#  methods: [PATCH]
#
#DeleteEntry:
#  path: /tracking/{date}
#  controller: App\Controller\MainController::deleteEntry
#  methods: [DELETE]