# https://symfony.com/doc/current/routing.html

api_entity_list:
  path: /tracking
  controller: App\Controller\EntityController::getAllEntries
  methods: [GET]

api_get_entity:
  path: /tracking/{date}
  controller: App\Controller\EntityController::getEntry
  methods: [GET]

api_delete_entity:
  path: /tracking/{date}
  controller: App\Controller\EntityController::deleteEntry
  methods: [DELETE]

api_add_entity:
  path: /tracking/{date}/begin/{!begin}
  controller: App\Controller\EntityController::addEntry
  defaults:
    begin: 0
  methods: [PUT]

api_change_entry:
  path: /tracking/{date}/begin/{begin}/end/{end}
  controller: App\Controller\MainController::changeEntry
  methods: [PATCH]