# https://symfony.com/doc/current/routing.html

api_entity_list:
  path: /tracking
  controller: App\Controller\EntityController::getAllEntries
  methods: [GET]

api_get_entity:
  path: /tracking/{date}
  controller: App\Controller\EntityController::getEntry
  methods: [GET]

api_delete_entity:
  path: /tracking/{date}
  controller: App\Controller\EntityController::deleteEntry
  methods: [DELETE]

api_add_entity:
  path: /tracking/{date}
  controller: App\Controller\EntityController::addEntry
  methods: [PUT]

api_update_entry:
  path: /tracking/{date}
  controller: App\Controller\MainController::updateEntry
  methods: [PATCH]